# Generated by Django 5.0.6 on 2024-06-22 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parent1_name', models.CharField(max_length=50)),
                ('parent2_name', models.CharField(max_length=50)),
                ('parent_type', models.CharField(choices=[('first_time', 'First Time Parent'), ('experienced', 'Experienced Parent')], max_length=20)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)])),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
