# Generated by Django 5.0.6 on 2024-06-22 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField(null=True)),
                ('min_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('parent_type', models.CharField(blank=True, choices=[('first_time', 'First Time Parent'), ('experienced', 'Experienced Parent')], max_length=20, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
