# Generated by Django 4.2.5 on 2024-06-22 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='updatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
